task_manager/config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    collection do
      get 'my'
      get 'shuffle'
    end
  end
  # root "articles#index"

  get '/logout', to: 'oauth_session#destroy'
  get '/auth/:provider/callback', to: 'oauth_session#create'
end

task_manager/app/models/account.rb
class Account < ApplicationRecord
  has_many :auth_providers

  EXECUTOR_ROLES = %w[employee]

  scope :executors, -> { where(role: EXECUTOR_ROLES) }

  scope :random, -> { order("random()") }
end

task_manager/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :assigned_to, class_name: 'Account'
  belongs_to :created_by, class_name: 'Account'

  validates :assigned_to, presence: true
  validates :created_by, presence: true

  enum state: {
    pending: 'pending',
    resolved: 'resolved'
  }

  def initialize(*, **)
    super

    self.state ||= :pending
    self.public_id ||= SecureRandom.uuid
  end

  def old_title
    attributes['title']
  end

  def title
    return if attributes['title'].nil?

    attributes['title'].split(/ - /).last
  end

  def jira_id
    return unless attributes['title'] =~ /\s\-\s/

    attributes['title'].split(/ - /).first
  end
end

task_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_account
    request.env['warden'].user
  end

  def require_user_logged_in!
    redirect_to '/' if current_account.nil?
  end
end

task_manager/app/controllers/oauth_session_controller.rb
class OauthSessionController < ApplicationController
  def destroy
    request.env['warden'].set_user(nil)

    redirect_to '/'
  end

  def create
    puts request.env['omniauth.auth']
    account = fetch_account || create_account

    request.env['warden'].set_user(account)
    redirect_to '/tasks'
  end

  private

  def fetch_account
    auth = AuthProvider.where(provider: request.env['omniauth.auth'].provider, uid: request.env['omniauth.auth'].uid).take
    return unless auth

    auth.account
  end

  def create_account
    Account.transaction do
      account = Account.find_by(public_id: payload['info']['public_id']) || Account.create!(
        public_id: payload['info']['public_id'],
        full_name: payload['info']['full_name'],
        email: payload['info']['email'],
        role: payload['info']['role']
      )
      account.auth_providers.create!(
        uid: payload.uid,
        provider: payload.provider,
        username: payload['info']['email'],
        user_info: payload.to_h
      )
    end
  end

  def payload
    request.env['omniauth.auth']
  end
end

task_manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_task, only: %i[ show edit update ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all.preload(:assigned_to, :created_by).order(:id)
    @tasks = @tasks.pending if params[:state] != 'all'
  end

  def my
    @tasks = Task.where(assigned_to: current_account).all.preload(:assigned_to, :created_by).order(:id)
  end

  def shuffle
    events = Task.pending.each_with_object([]) do |t, acc|
      prev_user_id = t.assigned_to_id
      t.update!(assigned_to: fetch_account_to_assign)
      if prev_user_id != t.assigned_to_id
        payload = {
          public_id: t.public_id,
          assigned_to: {public_id: t.assigned_to.public_id}
        }
        acc << build_event('tasks-stream', 'Task.Updated', meta: task_event_data, payload: task_data(t))
        acc << build_event('tasks', 'Task.Assigned', meta: task_event_data(1), payload: payload)
      end
    end.compact
    KAFKA_PRODUCER.produce_many_sync(events)
    redirect_to '/tasks'
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(**task_params)
    @task.created_by = current_account
    @task.assigned_to = fetch_account_to_assign

    respond_to do |format|
      if @task.save
        payload = task_data(@task)
        KAFKA_PRODUCER.produce_many_sync(
          [
            build_event('tasks-stream', 'Task.Created', meta: task_event_data, payload: payload),
            build_event('tasks', 'Task.Added', meta: task_event_data, payload: payload)
          ].compact
        )

        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        events = [
          build_event('tasks-stream', 'Task.Updated', meta: task_event_data, payload: task_data(@task))
        ]

        if @task.previous_changes.has_key?('state') && @task.resolved?
          payload = {
            public_id: @task.public_id,
            assigned_to: {public_id: @task.assigned_to.public_id}
          }
          events << build_event('tasks', 'Task.Resolved', meta: task_event_data(1), payload: payload)
        end

        KAFKA_PRODUCER.produce_many_sync(events.compact)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:public_id, :state, :assigned_to_id, :created_by_id, :title, :description)
    end

    def fetch_account_to_assign
      Account.executors.random.take
    end

    def task_event_data(v = 2)
      {
        event_id: SecureRandom.uuid,
        event_version: v,
        event_time: Time.now.to_s,
        producer: 'task_manager',
      }
    end

    def task_data(task, version=2)
      case version
      when 1
        {
          public_id: task.public_id,
          title: task.old_title,
          state: task.state,
          description: task.description,
          assigned_to: {
            public_id: task.assigned_to.public_id
          },
          created_by: {
            public_id: task.created_by.public_id
          }
        }
      when 2
        {
          public_id: task.public_id,
          title: task.title,
          jira_id: task.jira_id,
          state: task.state,
          description: task.description,
          assigned_to: {
            public_id: task.assigned_to.public_id
          },
          created_by: {
            public_id: task.created_by.public_id
          }
        }
      end
    end

    def build_event(topic, event_name, meta:, payload:)
      event = {
        **meta,
        event_name: event_name,
        data: payload
      }

      result = SchemaRegistry.validate_event(event, event_name.underscore, version: event[:event_version])

      if result.success?
        {topic: topic, payload: event.to_json}
      else
        puts "Event validation error: #{result.failure}"
        puts "Event data: #{event.inspect}"
      end
    end
end

task_manager/app/helpers/application_helper.rb
module ApplicationHelper
  def current_account
    request.env['warden'].user
  end

  def authenticated?(scope = nil)
    request.env['warden'].authenticated?
  end
end

task_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_account %>
      <%= current_account.full_name %> (<%= current_account.public_id %>)
    <% end %>
    <%= yield %>
  </body>
</html>

task_manager/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.select(:state, [['Pending', 'pending'], ['Resolved', 'resolved']]) %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

task_manager/app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Public:</strong>
    <%= task.public_id %>
  </p>

  <p>
    <strong>State:</strong>
    <%= task.state %>
  </p>

  <p>
    <strong>Assigned to:</strong>
    <%= task.assigned_to.full_name %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= task.created_by.full_name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>
</div>

task_manager/app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

task_manager/app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>
<%= link_to "Reassign tasks", shuffle_tasks_path %>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

task_manager/app/views/tasks/my.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

task_manager/app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

task_manager/app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>